version: '3'

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config.ini:/opt/urprofbot/config.ini
    networks:
      - backend

networks:
  backend:
